AWSTemplateFormatVersion: '2010-09-09'
Description: 'AWS App Runner service for Python Flask application'

Parameters:
  GitHubConnectionArn:
    Type: String
    Description: ARN of the GitHub connection

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: "Stack Configuration"
        Parameters:
          - DisableRollback

Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsHostnames: true
      EnableDnsSupport: true

  PrivateSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: 10.0.1.0/24
      AvailabilityZone: !Select [0, !GetAZs '']

  PrivateSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: 10.0.2.0/24
      AvailabilityZone: !Select [1, !GetAZs '']
  # Database Subnet Group
  DBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: Subnet group for RDS database
      SubnetIds: 
        - !Ref PrivateSubnet1
        - !Ref PrivateSubnet2

  # Database Security Group
  DatabaseSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for RDS instance
      VpcId: !Ref VPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 5432
          ToPort: 5432
          SourceSecurityGroupId: !Ref AppRunnerSecurityGroup

  # RDS Instance
  PostgresDB:
    Type: AWS::RDS::DBInstance
    Properties:
      DBName: myappdb
      Engine: postgres
      EngineVersion: 15.4
      DBInstanceClass: db.t3.micro
      AllocatedStorage: 20
      StorageType: gp2
      MasterUsername: !Sub '{{resolve:secretsmanager:${DatabaseSecret}:SecretString:username}}'
      MasterUserPassword: !Sub '{{resolve:secretsmanager:${DatabaseSecret}:SecretString:password}}'
      DBSubnetGroupName: !Ref DBSubnetGroup
      VPCSecurityGroups: 
        - !Ref DatabaseSecurityGroup
      PubliclyAccessible: false

  # Database Credentials in Secrets Manager
  DatabaseSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub ${AWS::StackName}-db-credentials
      GenerateSecretString:
        SecretStringTemplate: '{"username": "dbadmin"}'
        GenerateStringKey: "password"
        PasswordLength: 16
        ExcludeCharacters: '"@/\'

  AppRunnerServiceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: tasks.apprunner.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSAppRunnerServicePolicyForECRAccess
      Policies:
        - PolicyName: SecretsManagerAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: secretsmanager:GetSecretValue
                Resource: 
                  - !Ref DatabaseSecret
                  - arn:aws:secretsmanager:us-east-1:182399709699:secret:flask_app_secrets-f2tk0b

  AppRunnerService:
    Type: AWS::AppRunner::Service
    DeletionPolicy: Retain
    Properties:
      ServiceName: my-flask-app
      SourceConfiguration:
        AuthenticationConfiguration:
          ConnectionArn: !Ref GitHubConnectionArn
        AutoDeploymentsEnabled: true
        CodeRepository:
          RepositoryUrl: https://github.com/siliconshells/DE_FinalProject_KEH
          SourceCodeVersion:
            Type: BRANCH
            Value: main
          CodeConfiguration:
            CodeConfigurationValues:
              Runtime: PYTHON_3
              BuildCommand: python -m pip install --upgrade pip && pip3 install -r requirements.txt
              StartCommand: python app.py
              Port: 8080
              RuntimeEnvironmentVariables:
                - Name: FLASK_ENV
                  Value: production
                - Name: DB_SECRET_ARN
                  Value: !Ref DatabaseSecret
                - Name: DB_HOST
                  Value: !GetAtt PostgresDB.Endpoint.Address
                - Name: DB_PORT
                  Value: !GetAtt PostgresDB.Endpoint.Port

            ConfigurationSource: API
      InstanceConfiguration:
        InstanceRoleArn: !GetAtt AppRunnerServiceRole.Arn
        Cpu: '1 vCPU'
        Memory: '2 GB'
        InstanceRoleArn: !GetAtt AppRunnerServiceRole.Arn
      HealthCheckConfiguration:
        Protocol: HTTP
        Path: /health
        HealthyThreshold: 1
        UnhealthyThreshold: 5
        Interval: 10
        Timeout: 5
      AutoScalingConfigurationArn: !Ref AppRunnerAutoScalingConfiguration
      Tags:
        - Key: Environment
          Value: Production

  AppRunnerAutoScalingConfiguration:
    Type: AWS::AppRunner::AutoScalingConfiguration
    Properties:
      AutoScalingConfigurationName: my-flask-app-autoscaling
      MaxConcurrency: 100
      MinSize: 1
      MaxSize: 10

Outputs:
  ServiceUrl:
    Description: URL of the App Runner service
    Value: !GetAtt AppRunnerService.ServiceUrl
  DatabaseEndpoint:
    Description: Database endpoint
    Value: !GetAtt PostgresDB.Endpoint.Address
  DatabaseSecret:
    Description: Database secret ARN
    Value: !Ref DatabaseSecret