AWSTemplateFormatVersion: '2010-09-09'
Description: 'CloudFormation template for Flask app on App Runner with PostgreSQL'

Parameters:
  GitHubRepo:
    Type: String
    Description: GitHub repository URL

  GitHubBranch:
    Type: String
    Description: GitHub branch name
    Default: main

  DBName:
    Type: String
    Description: Database name

  DBUsername:
    Type: String
    Description: Database username

  DBPassword:
    Type: String
    Description: Database password
    NoEcho: true

  # New parameter in place of GitHubConnection
  GitHubConnectionArn:
    Type: String
    Description: ARN of the manually created GitHub connection

Resources:
  AppRunnerService:
    Type: AWS::AppRunner::Service
    Properties:
      SourceConfiguration:
        AuthenticationConfiguration:
          ConnectionArn: !Ref GitHubConnectionArn
        AutoDeploymentsEnabled: true
        CodeRepository:
          RepositoryUrl: !Ref GitHubRepo
          SourceCodeVersion:
            Type: BRANCH
            Value: !Ref GitHubBranch
      InstanceConfiguration:
        InstanceRoleArn: !GetAtt AppRunnerInstanceRole.Arn

  # GitHubConnection:
  #   Type: AWS::AppRunner::Connection
  #   Properties:
  #     ConnectionName: GitHubConnection
  #     ProviderType: GITHUB

  AppRunnerInstanceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: tasks.apprunner.amazonaws.com
            Action: 'sts:AssumeRole'
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSAppRunnerServicePolicyForECRAccess

  PostgreSQLInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      DBName: !Ref DBName
      Engine: postgres
      MasterUsername: !Ref DBUsername
      MasterUserPassword: !Ref DBPassword
      DBInstanceClass: db.t3.micro
      AllocatedStorage: '20'
      PubliclyAccessible: false

Outputs:
  AppRunnerServiceUrl:
    Description: "App Runner Service URL"
    Value: !GetAtt AppRunnerService.ServiceUrl

  DatabaseEndpoint:
    Description: "PostgreSQL Database Endpoint"
    Value: !GetAtt PostgreSQLInstance.Endpoint.Address

  DatabasePort:
    Description: "PostgreSQL Database Port"
    Value: !GetAtt PostgreSQLInstance.Endpoint.Port
