name: Deploy CloudFormation Stack

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: List and Delete All App Runner Services
      run: |
        # List all App Runner services
        echo "Fetching all App Runner services..."
        SERVICES=$(aws apprunner list-services --query "ServiceSummaryList[*].ServiceArn" --output text)

        if [ -z "$SERVICES" ]; then
          echo "No App Runner services found."
        else
          echo "Deleting App Runner services..."
          for SERVICE_ARN in $SERVICES; do
            echo "Deleting service: $SERVICE_ARN"
            aws apprunner pause-service --service-arn $SERVICE_ARN
            aws apprunner delete-service --service-arn $SERVICE_ARN
          done
          echo "All App Runner services deleted."
        fi

    - name: Delete existing stack
      run: |
        aws cloudformation delete-stack --stack-name my-flask-app-stack
        aws cloudformation wait stack-delete-complete --stack-name my-flask-app-stack

    - name: Deploy CloudFormation stack
      uses: aws-actions/aws-cloudformation-github-deploy@v1
      with:
        name: my-flask-app-stack
        template: app-runner-stack.yaml
        parameter-overrides: "GitHubConnectionArn=${{ secrets.REPOSITORY_CONNECTION_ARN }}"

    - name: Get Service URL
      run: |
        SERVICE_URL=$(aws cloudformation describe-stacks --stack-name my-flask-app-stack --query 'Stacks[0].Outputs[?OutputKey==`ServiceUrl`].OutputValue' --output text)
        
        echo "App Runner Service URL: $SERVICE_URL"
        
        # If you want to set this as an output variable in GitHub Actions
        echo "SERVICE_URL=$SERVICE_URL" >> $GITHUB_ENV
        
        # Create a markdown summary
        echo "## Deployment URL" >> $GITHUB_STEP_SUMMARY
        echo "✨ **App Runner URL:** $SERVICE_URL" >> $GITHUB_STEP_SUMMARY
  