name: Deploy CloudFormation Stack

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Delete existing stack
      run: |
        aws cloudformation delete-stack --stack-name my-flask-app-stack
        aws cloudformation wait stack-delete-complete --stack-name my-flask-app-stack

    - name: Deploy CloudFormation stack
      uses: aws-actions/aws-cloudformation-github-deploy@v1
      with:
        name: my-flask-app-stack
        template: app-runner-stack.yaml
        parameter-overrides: "GitHubConnectionArn=${{ secrets.REPOSITORY_CONNECTION_ARN }}"

    - name: Update README with URL
      run: |
        SERVICE_URL=$(aws cloudformation describe-stacks \
          --stack-name my-flask-app-stack \
          --query 'Stacks[0].Outputs[?OutputKey==`ServiceUrl`].OutputValue' \
          --output text)
        
        # Update or add the URL section
        if grep -q "## Deployment URL" README.md; then
          # Update existing URL
          sed -i "/## Deployment URL/,/^$/c\## Deployment URL\n- App Runner URL: $SERVICE_URL\n\nLast deployed: $(date '+%Y-%m-%d %H:%M:%S UTC')\n" README.md
        else
          # Add new URL section at the top (after the first heading)
          sed -i "1{p;s/.*//;a\## Deployment URL\n- App Runner URL: $SERVICE_URL\n\nLast deployed: $(date '+%Y-%m-%d %H:%M:%S UTC')\n" -e "}" README.md
        fi
        
        # Configure Git
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'
        
        # Check if there are changes to commit
        if git diff --quiet README.md; then
          echo "No changes to README.md"
        else
          git add README.md
          git commit -m "Update deployment URL [skip ci]"
          git push
        fi