name: Deploy CloudFormation Stack

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Delete existing stack
      run: |
        aws cloudformation delete-stack --stack-name my-flask-app-stack
        aws cloudformation wait stack-delete-complete --stack-name my-flask-app-stack

    - name: Deploy CloudFormation stack
      uses: aws-actions/aws-cloudformation-github-deploy@v1
      with:
        name: my-flask-app-stack
        template: app-runner-stack.yaml
        parameter-overrides: "GitHubConnectionArn=${{ secrets.REPOSITORY_CONNECTION_ARN }}"

    - name: Display the new URL
      run: |
        SERVICE_ARN=$(aws cloudformation describe-stacks  --stack-name my-flask-app-stack  --query 'Stacks[0].Outputs[?OutputKey==`ServiceUrl`].OutputValue' --output text)        
    #    SERVICE_ARN=$(aws cloudformation describe-stacks  --stack-name my-flask-app-stack  --query 'Stacks[0].Outputs[?OutputKey==`ServiceArn`].OutputValue' --output text)        
    #    aws apprunner associate-custom-domain  --service-arn $SERVICE_ARN  --domain-name de-recipe-generator.com --enable-www-subdomain

    # - name: Wait for domain association
    #   run: |
    #     aws apprunner wait associate-custom-domain  --service-arn $SERVICE_ARN  --domain-name de-recipe-generator.com

    # - name: Update Route 53 Record
    #   run: |
    #     aws route53 change-resource-record-sets --hosted-zone-id Z07107629D9IQB919IBH --change-batch '{
    #       "Changes": [{
    #         "Action": "UPSERT",
    #         "ResourceRecordSet": {
    #           "Name": "de-recipe-generator.com",
    #           "Type": "A",
    #           "AliasTarget": {
    #             "HostedZoneId": "Z01915732ZBZKC8W32UF0",
    #             "DNSName": 'Stacks[0].Outputs[?OutputKey==`ServiceArn`].OutputValue',
    #             "EvaluateTargetHealth": true