name: Deploy to AWS App Runner

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Deploy to AWS CloudFormation
      uses: aws-actions/aws-cloudformation-github-deploy@v1
      with:
        name: my-apprunner-postgres-stack
        template: app-runner-postgres.yml
        parameter-overrides: >-
          GitHubRepo=${{ github.repository }},
          GitHubBranch=${{ github.ref_name }},
          DBName=${{ secrets.DB_NAME }},
          DBUsername=${{ secrets.DB_USERNAME }},
          DBPassword=${{ secrets.DB_PASSWORD }},
          GitHubConnectionArn=${{ secrets.APPRUNNER_CONNECTION_ARN }}
